#!/bin/sh /etc/rc.common

# start after networking
START=22

LOGGER="logger -s -t autowifi -p 6"

boot() {
	$LOGGER "Invoking Doodle3D WiFi box network auto-initialization..."
	/usr/share/lua/wifibox/script/d3dapi autowifi
	
	$LOGGER "Start signing in..."
	/usr/share/lua/wifibox/script/signin.sh > /dev/null 2> /dev/null &
}

#start() {
#	$LOGGER "dummy start"
#}

#stop() {
#	$LOGGER "dummy stop"
#}