#!/bin/sh /etc/rc.common

START=18
LOGGER="logger -s -t autowifi -p 6"

boot() {
	$LOGGER "dummy boot"
	#/www/cgi-bin/wfcf op=auto
}

start() {
	$LOGGER "dummy start"
}

stop() {
	$LOGGER "dummy stop"
}
